# Generated by Django 5.2.4 on 2025-08-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
