# Generated by Django 5.2.4 on 2025-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_shippingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='first_kana_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_kana_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
