# Generated by Django 5.2.4 on 2025-08-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_shippingaddress_is_default_favorite'),
        ('products', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
    ]
