# Generated by Django 5.2.4 on 2025-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default'], name='accounts_sh_user_id_3af404_idx'),
        ),
    ]
