# Generated by Django 5.2.4 on 2025-08-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id_alter_order_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('FA', 'Failed'), ('RE', 'Refunded')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('SH', 'Shipped'), ('DE', 'Delivered')], default='PE', max_length=2),
        ),
    ]
