# Generated by Django 5.2.4 on 2025-08-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PE', '保留中'), ('PA', '支払い済み'), ('FA', '支払い失敗'), ('RE', '返金済み')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('PE', '発送準備中'), ('SH', '発送済み'), ('DE', '配達済み')], default='PE', max_length=2),
        ),
    ]
