# Generated by Django 5.2.4 on 2025-08-24 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date', '-id'], name='orders_orde_date_b374ae_idx'),
        ),
    ]
