# Generated by Django 5.2.8 on 2026-01-12 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
