# Generated by Django 5.2.4 on 2025-08-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='published_at',
        ),
    ]
