# Generated by Django 5.2.8 on 2026-01-12 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
